// Crowe Logic release site: branded download page at "/", installer objects
// streamed from the crowe-releases R2 bucket under /desktop/* and /brand/*.
const VERSION = "0.11.0";

// Inline copy of assets/mark.svg (generated by scripts/gen-mark.js) so the page
// renders its logo without an R2 brand object; re-inline if the mark regenerates.
const MARK_SVG = `<svg class="mark" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <polygon points="62.39,7.07 60.00,5.69 12.96,32.84 27.36,41.16 60.00,22.31 62.39,23.69" fill="#3766C0"/>
  <polygon points="12.96,32.84 12.96,87.16 27.36,78.84 27.36,41.16" fill="#2E5AAD"/>
  <polygon points="12.96,87.16 60.00,114.31 95.85,93.61 95.85,76.99 60.00,97.69 27.36,78.84" fill="#274C97"/>
  <polygon points="62.39,18.04 60.00,16.66 22.47,38.33 22.47,81.67 60.00,103.34 95.85,82.64 95.85,76.99 60.00,97.69 27.36,78.84 27.36,41.16 60.00,22.31 62.39,23.69" fill="#13294F"/>
  <polygon points="92.64,54.04 107.04,45.72 107.04,64.12 92.64,72.44" fill="#2E5AAD"/>
  <polygon points="92.64,54.04 97.53,51.21 97.53,69.61 92.64,72.44" fill="#13294F"/>
  <polygon points="69.68,99.59 42.16,83.71 55.76,75.85 69.68,83.89" fill="#CE8710"/>
  <polygon points="42.16,83.71 42.16,45.03 67.82,30.22 67.82,45.92 55.76,52.89 55.76,75.85" fill="#EFA71B"/>
  <polygon points="51.14,78.52 51.14,50.22 67.82,40.58 67.82,45.92 55.76,52.89 55.76,75.85" fill="#A96F08"/>
  <polygon points="67.02,24.73 106.46,38.07 67.02,51.41" fill="#EFA71B"/>
  <polygon points="67.02,51.41 106.46,38.07 107.27,40.48 67.83,53.82" fill="#A96F08"/>
</svg>`;
const MARK_ICON = "data:image/svg+xml," + encodeURIComponent(MARK_SVG.replace(' class="mark"', ""));

const PAGE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Crowe Logic releases</title>
<meta name="description" content="Download the Crowe Logic desktop app for Windows, macOS, and Linux." />
<link rel="icon" type="image/svg+xml" href="${MARK_ICON}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
<style>
:root { --paper:#f7f3ea; --panel:#fdfbf5; --ink:#1a1714; --gold:#b8893a; --dim:#6b6457; --line:rgba(26,23,20,.12); }
* { box-sizing:border-box; margin:0; }
body { background:var(--paper); color:var(--ink); font-family:Inter,system-ui,sans-serif; line-height:1.6; }
.wrap { max-width:920px; margin:0 auto; padding:0 24px; }
header { border-bottom:1px solid var(--line); }
header .wrap { display:flex; align-items:center; gap:12px; padding-top:16px; padding-bottom:16px; }
header .mark { width:28px; height:28px; }
header .name { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:18px; }
header .tag { font-family:'JetBrains Mono',monospace; font-size:11px; color:var(--dim); border:1px solid var(--line); border-radius:999px; padding:2px 10px; margin-left:4px; }
main { padding:56px 0 64px; }
h1 { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:40px; line-height:1.1; letter-spacing:-0.01em; }
.sub { color:var(--dim); font-size:15px; max-width:560px; margin:16px 0 8px; }
.ver { display:inline-block; font-family:'JetBrains Mono',monospace; font-size:12px; color:var(--gold); border:1px solid var(--gold); border-radius:999px; padding:2px 12px; margin:8px 0 40px; }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:16px; }
.card { background:var(--panel); border:1px solid var(--line); border-radius:14px; padding:24px; display:flex; flex-direction:column; gap:12px; }
.card h2 { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:20px; }
.card .meta { font-family:'JetBrains Mono',monospace; font-size:11.5px; color:var(--dim); }
.card p { font-size:13.5px; color:var(--dim); flex:1; }
.btn { display:inline-block; background:var(--ink); color:var(--paper); text-decoration:none; font-size:14px; font-weight:500; border-radius:10px; padding:10px 18px; text-align:center; }
.btn:hover { background:var(--gold); }
.alt { font-size:13px; }
.alt a { color:var(--gold); }
code, pre { font-family:'JetBrains Mono',monospace; font-size:12px; }
pre { background:#17150f; color:#e9e2cf; border-radius:8px; padding:10px 14px; overflow-x:auto; }
.note { border-left:2px solid var(--gold); padding-left:14px; margin-top:24px; font-size:13px; color:var(--dim); }
section.checks { margin-top:56px; border-top:1px solid var(--line); padding-top:32px; }
section.checks h3 { font-family:Fraunces,Georgia,serif; font-size:18px; font-weight:600; margin-bottom:8px; }
section.checks p { font-size:13.5px; color:var(--dim); margin-bottom:10px; }
section.presale { margin:48px 0 0; background:var(--panel); border:1px solid var(--gold); border-radius:14px; padding:28px; }
section.presale .eyebrow { font-family:'JetBrains Mono',monospace; font-size:11px; letter-spacing:.12em; text-transform:uppercase; color:var(--gold); margin-bottom:10px; }
section.presale h2 { font-family:Fraunces,Georgia,serif; font-size:26px; font-weight:600; margin-bottom:10px; }
section.presale p { font-size:14px; color:var(--dim); max-width:600px; }
section.presale .price { font-family:Fraunces,Georgia,serif; font-size:22px; margin:14px 0 4px; }
section.presale .price small { font-size:13px; color:var(--dim); font-family:Inter,system-ui,sans-serif; }
section.presale form { display:flex; gap:10px; margin-top:16px; flex-wrap:wrap; }
section.presale input[type=email] { flex:1; min-width:220px; border:1px solid var(--line); border-radius:10px; padding:10px 14px; font-size:14px; font-family:Inter,system-ui,sans-serif; background:#fff; }
section.presale button { background:var(--gold); color:#fff; border:0; border-radius:10px; padding:10px 22px; font-size:14px; font-weight:600; cursor:pointer; }
section.presale button:hover { background:var(--ink); }
section.presale .err { color:#a33; font-size:13px; margin-top:10px; display:none; }
footer { border-top:1px solid var(--line); padding:24px 0 40px; color:var(--dim); font-size:12.5px; }
footer .wrap { display:flex; justify-content:space-between; gap:16px; flex-wrap:wrap; }
</style>
</head>
<body>
<header>
  <div class="wrap">
    ${MARK_SVG}
    <span class="name">Crowe Logic</span>
    <span class="tag">releases</span>
  </div>
</header>
<main>
  <div class="wrap">
    <h1>Crowe Logic desktop</h1>
    <p class="sub">The operator for your workspace. Chat, a real terminal, reviewable edits, and an in-app browser, signed in with your Crowe ID.</p>
    <span class="ver">v${VERSION}</span>
    <div class="grid">
      <div class="card">
        <h2>Windows</h2>
        <span class="meta">64-bit installer</span>
        <p>The Windows build is being validated and will return in the next cross-platform release.</p>
        <span class="meta">Coming soon</span>
      </div>
      <div class="card">
        <h2>macOS</h2>
        <span class="meta">Apple Silicon dmg</span>
        <p>Open the dmg and drag Crowe Logic to Applications. This build is Developer ID signed, Apple notarized, and stapled.</p>
        <a class="btn" href="/desktop/${VERSION}/CroweLogic-${VERSION}-arm64.dmg">Download for macOS</a>
      </div>
      <div class="card">
        <h2>Linux</h2>
        <span class="meta">x86_64 deb and AppImage</span>
        <p>The Linux packages are being validated and will return in the next cross-platform release.</p>
        <span class="meta">Coming soon</span>
      </div>
    </div>
    <section class="checks">
      <h3>Verify your download</h3>
      <p>With <a style="color:var(--gold)" href="/desktop/${VERSION}/SHA256SUMS">SHA256SUMS</a> in your download folder:</p>
      <pre>sha256sum -c SHA256SUMS --ignore-missing</pre>
    </section>
  </div>
</main>
<footer>
  <div class="wrap">
    <span>Crowe Logic, Inc.</span>
    <span>Questions: michael@crowelogic.com</span>
  </div>
</footer>
</body>
</html>`;

const TYPES = {
  ".exe": "application/octet-stream",
  ".dmg": "application/octet-stream",
  ".deb": "application/octet-stream",
  ".AppImage": "application/octet-stream",
  ".md": "text/markdown; charset=utf-8",
  ".png": "image/png",
};

function contentTypeFor(key, stored) {
  if (stored && stored !== "application/octet-stream") return stored;
  const ext = Object.keys(TYPES).find((e) => key.endsWith(e));
  return ext ? TYPES[ext] : stored || "application/octet-stream";
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
    }

    if (path === "/" || path === "/index.html") {
      return new Response(request.method === "HEAD" ? null : PAGE, {
        headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300" },
      });
    }

    if (path.startsWith("/desktop/") || path.startsWith("/brand/")) {
      const key = path.slice(1);
      const object = await env.RELEASES.get(key);
      if (!object) return new Response("Not found", { status: 404 });
      const headers = new Headers();
      object.writeHttpMetadata(headers);
      headers.set("content-type", contentTypeFor(key, headers.get("content-type")));
      headers.set("etag", object.httpEtag);
      headers.set("cache-control", "public, max-age=3600");
      headers.set("content-length", String(object.size));
      if (request.method === "HEAD") { object.body?.cancel?.(); return new Response(null, { headers }); }
      return new Response(object.body, { headers });
    }

    return new Response("Not found", { status: 404 });
  },
};
