// Crowe Logic release site: branded download page at "/", installer objects
// streamed from the crowe-releases R2 bucket under /desktop/* and /brand/*.

// Inline copy of assets/mark.svg (generated by scripts/gen-mark.js) so the page
// renders its logo without an R2 brand object; re-inline if the mark regenerates.
const MARK_SVG = `<svg class="mark" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120">
  <polygon points="64.40,51.05 64.19,48.54 64.07,46.12 64.06,43.73 64.20,41.38 64.54,39.06 65.10,36.75 65.92,34.48 67.06,32.24 68.55,30.06 70.45,27.98 72.78,26.05 75.69,24.29 74.28,21.53 70.94,22.98 67.91,24.82 65.27,26.94 63.02,29.29 61.13,31.82 59.60,34.47 58.38,37.21 57.45,39.99 56.75,42.78 56.24,45.55 55.87,48.30 55.60,50.95" fill="#1a1714"/>
  <polygon points="65.12,33.35 65.16,32.22 65.21,31.12 65.29,30.04 65.42,28.99 65.60,27.96 65.85,26.96 66.19,25.98 66.61,25.04 67.15,24.14 67.80,23.29 68.59,22.50 69.60,21.74 68.10,19.68 66.93,20.50 65.85,21.47 64.94,22.54 64.18,23.67 63.57,24.84 63.08,26.04 62.70,27.25 62.42,28.45 62.21,29.65 62.05,30.83 61.93,32.00 61.83,33.14" fill="#1a1714"/>
  <polygon points="64.41,34.60 65.32,33.94 66.22,33.30 67.12,32.71 68.03,32.15 68.95,31.66 69.89,31.25 70.87,30.91 71.87,30.67 72.91,30.54 73.98,30.53 75.09,30.66 76.31,30.98 77.01,28.54 75.65,28.12 74.21,27.87 72.81,27.81 71.45,27.91 70.15,28.14 68.91,28.50 67.73,28.94 66.60,29.46 65.53,30.03 64.50,30.64 63.51,31.26 62.54,31.89" fill="#1a1714"/>
  <polygon points="69.95,59.34 72.02,57.90 74.06,56.58 76.12,55.38 78.23,54.33 80.41,53.46 82.68,52.79 85.07,52.37 87.57,52.23 90.21,52.44 92.96,53.04 95.80,54.09 98.77,55.74 100.45,53.13 97.53,50.97 94.42,49.26 91.26,48.03 88.10,47.26 84.97,46.89 81.91,46.89 78.93,47.20 76.06,47.78 73.29,48.57 70.63,49.52 68.07,50.57 65.64,51.66" fill="#1a1714"/>
  <polygon points="85.64,51.11 86.64,50.58 87.62,50.07 88.59,49.60 89.57,49.19 90.55,48.83 91.54,48.55 92.55,48.35 93.58,48.25 94.63,48.26 95.69,48.41 96.77,48.69 97.93,49.18 98.97,46.86 97.68,46.25 96.29,45.81 94.91,45.55 93.55,45.46 92.23,45.51 90.95,45.69 89.72,45.97 88.53,46.32 87.39,46.74 86.29,47.19 85.22,47.67 84.17,48.16" fill="#1a1714"/>
  <polygon points="84.20,51.12 85.23,51.58 86.23,52.04 87.20,52.52 88.13,53.03 89.01,53.58 89.85,54.19 90.63,54.87 91.34,55.61 91.97,56.45 92.51,57.37 92.95,58.40 93.29,59.62 95.75,59.00 95.43,57.61 94.93,56.24 94.28,55.00 93.52,53.87 92.66,52.86 91.74,51.97 90.76,51.16 89.75,50.45 88.72,49.81 87.68,49.22 86.64,48.67 85.62,48.14" fill="#1a1714"/>
  <polygon points="65.55,68.28 67.83,69.36 69.99,70.46 72.06,71.65 74.02,72.95 75.87,74.40 77.58,76.04 79.14,77.89 80.52,80.00 81.66,82.38 82.51,85.06 83.01,88.05 83.08,91.44 86.17,91.60 86.59,87.99 86.51,84.44 85.99,81.09 85.08,77.97 83.84,75.07 82.31,72.42 80.55,70.00 78.61,67.79 76.54,65.79 74.39,63.96 72.20,62.28 70.04,60.72" fill="#1a1714"/>
  <polygon points="80.52,77.76 81.48,78.36 82.41,78.95 83.30,79.56 84.15,80.20 84.95,80.87 85.69,81.59 86.37,82.37 86.97,83.21 87.48,84.12 87.89,85.11 88.18,86.19 88.34,87.44 90.87,87.18 90.75,85.75 90.44,84.33 89.97,83.01 89.37,81.79 88.66,80.67 87.87,79.65 87.01,78.72 86.11,77.87 85.18,77.09 84.23,76.36 83.28,75.67 82.34,75.01" fill="#1a1714"/>
  <polygon points="79.79,76.52 79.91,77.63 80.01,78.73 80.08,79.81 80.10,80.87 80.06,81.92 79.95,82.95 79.76,83.96 79.47,84.95 79.06,85.91 78.53,86.85 77.86,87.74 76.97,88.63 78.74,90.46 79.79,89.49 80.72,88.37 81.47,87.19 82.07,85.97 82.51,84.72 82.83,83.47 83.03,82.22 83.14,80.99 83.19,79.77 83.18,78.58 83.13,77.41 83.08,76.26" fill="#1a1714"/>
  <polygon points="55.60,68.95 55.81,71.46 55.93,73.88 55.94,76.27 55.80,78.62 55.46,80.94 54.90,83.25 54.08,85.52 52.94,87.76 51.45,89.94 49.55,92.02 47.22,93.95 44.31,95.71 45.72,98.47 49.06,97.02 52.09,95.18 54.73,93.06 56.98,90.71 58.87,88.18 60.40,85.53 61.62,82.79 62.55,80.01 63.25,77.22 63.76,74.45 64.13,71.70 64.40,69.05" fill="#1a1714"/>
  <polygon points="54.88,86.65 54.84,87.78 54.79,88.88 54.71,89.96 54.58,91.01 54.40,92.04 54.15,93.04 53.81,94.02 53.39,94.96 52.85,95.86 52.20,96.71 51.41,97.50 50.40,98.26 51.90,100.32 53.07,99.50 54.15,98.53 55.06,97.46 55.82,96.33 56.43,95.16 56.92,93.96 57.30,92.75 57.58,91.55 57.79,90.35 57.95,89.17 58.07,88.00 58.17,86.86" fill="#1a1714"/>
  <polygon points="55.59,85.40 54.68,86.06 53.78,86.70 52.88,87.29 51.97,87.85 51.05,88.34 50.11,88.75 49.13,89.09 48.13,89.33 47.09,89.46 46.02,89.47 44.91,89.34 43.69,89.02 42.99,91.46 44.35,91.88 45.79,92.13 47.19,92.19 48.55,92.09 49.85,91.86 51.09,91.50 52.27,91.06 53.40,90.54 54.47,89.97 55.50,89.36 56.49,88.74 57.46,88.11" fill="#1a1714"/>
  <polygon points="50.05,60.66 47.98,62.10 45.94,63.42 43.88,64.62 41.77,65.67 39.59,66.54 37.32,67.21 34.93,67.63 32.43,67.77 29.79,67.56 27.04,66.96 24.20,65.91 21.23,64.26 19.55,66.87 22.47,69.03 25.58,70.74 28.74,71.97 31.90,72.74 35.03,73.11 38.09,73.11 41.07,72.80 43.94,72.22 46.71,71.43 49.37,70.48 51.93,69.43 54.36,68.34" fill="#1a1714"/>
  <polygon points="34.36,68.89 33.36,69.42 32.38,69.93 31.41,70.40 30.43,70.81 29.45,71.17 28.46,71.45 27.45,71.65 26.42,71.75 25.37,71.74 24.31,71.59 23.23,71.31 22.07,70.82 21.03,73.14 22.32,73.75 23.71,74.19 25.09,74.45 26.45,74.54 27.77,74.49 29.05,74.31 30.28,74.03 31.47,73.68 32.61,73.26 33.71,72.81 34.78,72.33 35.83,71.84" fill="#1a1714"/>
  <polygon points="35.80,68.88 34.77,68.42 33.77,67.96 32.80,67.48 31.87,66.97 30.99,66.42 30.15,65.81 29.37,65.13 28.66,64.39 28.03,63.55 27.49,62.63 27.05,61.60 26.71,60.38 24.25,61.00 24.57,62.39 25.07,63.76 25.72,65.00 26.48,66.13 27.34,67.14 28.26,68.03 29.24,68.84 30.25,69.55 31.28,70.19 32.32,70.78 33.36,71.33 34.38,71.86" fill="#1a1714"/>
  <polygon points="54.45,51.72 52.17,50.64 50.01,49.54 47.94,48.35 45.98,47.05 44.13,45.60 42.42,43.96 40.86,42.11 39.48,40.00 38.34,37.62 37.49,34.94 36.99,31.95 36.92,28.56 33.83,28.40 33.41,32.01 33.49,35.56 34.01,38.91 34.92,42.03 36.16,44.93 37.69,47.58 39.45,50.00 41.39,52.21 43.46,54.21 45.61,56.04 47.80,57.72 49.96,59.28" fill="#1a1714"/>
  <polygon points="39.48,42.24 38.52,41.64 37.59,41.05 36.70,40.44 35.85,39.80 35.05,39.13 34.31,38.41 33.63,37.63 33.03,36.79 32.52,35.88 32.11,34.89 31.82,33.81 31.66,32.56 29.13,32.82 29.25,34.25 29.56,35.67 30.03,36.99 30.63,38.21 31.34,39.33 32.13,40.35 32.99,41.28 33.89,42.13 34.82,42.91 35.77,43.64 36.72,44.33 37.66,44.99" fill="#1a1714"/>
  <polygon points="40.21,43.48 40.09,42.37 39.99,41.27 39.92,40.19 39.90,39.13 39.94,38.08 40.05,37.05 40.24,36.04 40.53,35.05 40.94,34.09 41.47,33.15 42.14,32.26 43.03,31.37 41.26,29.54 40.21,30.51 39.28,31.63 38.53,32.81 37.93,34.03 37.49,35.28 37.17,36.53 36.97,37.78 36.86,39.01 36.81,40.23 36.82,41.42 36.87,42.59 36.92,43.74" fill="#1a1714"/>
  <polygon points="60.00,44.20 73.68,52.10 73.68,67.90 60.00,75.80 46.32,67.90 46.32,52.10" fill="#EFA71B"/>
</svg>`;
const MARK_ICON = "data:image/svg+xml," + encodeURIComponent(MARK_SVG.replace(' class="mark"', ""));

function href(version, name) {
  return `/desktop/${encodeURIComponent(version)}/${encodeURIComponent(name)}`;
}

function escapeHtml(s) {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
}

function card(title, meta, body, rel, primary, secondary, secondaryLabel) {
  const buttons = primary
    ? `<a class="btn" href="${href(rel.version, primary)}">Download for ${escapeHtml(title)}</a>` +
      (secondary ? `\n        <span class="alt"><a href="${href(rel.version, secondary)}">${escapeHtml(secondaryLabel)}</a></span>` : "")
    : `<span class="meta">Not in this release</span>`;
  return `<div class="card">
        <h2>${escapeHtml(title)}</h2>
        <span class="meta">${escapeHtml(meta)}</span>
        <p>${escapeHtml(body)}</p>
        ${buttons}
      </div>`;
}

// The page used to hardcode a version and installer filenames, which drifted
// three releases out of date and linked a Windows installer that had never been
// built under that name. Read the channel manifests the updater reads instead,
// so the page cannot disagree with what was actually published.
async function readManifest(env, key) {
  const object = await env.RELEASES.get(key);
  if (!object) return null;
  const text = await object.text();
  const version = /^version:\s*(\S+)/m.exec(text);
  if (!version) return null;
  return { version: version[1], files: [...text.matchAll(/^\s+- url:\s*(.+?)\s*$/gm)].map((m) => m[1]) };
}

async function catalog(env) {
  // These paths must match electron-builder's ${os} macro in the publish url,
  // which expands to mac, win and linux.
  const [mac, win, lin] = await Promise.all([
    readManifest(env, "desktop/channel/mac/latest-mac.yml"),
    readManifest(env, "desktop/channel/win/latest.yml"),
    readManifest(env, "desktop/channel/linux/latest-linux.yml"),
  ]);

  // Platforms can lag each other, so show the newest version any of them
  // reached and only offer the installers that belong to it.
  const versions = [mac, win, lin].filter(Boolean).map((m) => m.version);
  if (versions.length === 0) return null;
  const version = versions.sort(compareVersions).pop();
  const at = (m) => (m && m.version === version ? m.files : []);
  const pick = (m, re) => at(m).find((f) => re.test(f)) || null;

  // Match the architecture explicitly rather than taking the first dmg in the
  // feed. electron-builder writes x64 ahead of arm64, so "first dmg" handed
  // every Apple Silicon visitor the Intel build under a card that said Apple
  // Silicon - and the download works, so nobody would have reported it.
  return {
    version,
    windows: pick(win, /\.exe$/),
    macos: pick(mac, /arm64\.dmg$/) || pick(mac, /\.dmg$/),
    macosIntel: pick(mac, /x64\.dmg$/),
    appimage: pick(lin, /\.AppImage$/),
    deb: pick(lin, /\.deb$/),
  };
}

function compareVersions(a, b) {
  const pa = a.split(/[.-]/);
  const pb = b.split(/[.-]/);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const na = Number(pa[i]);
    const nb = Number(pb[i]);
    if (Number.isNaN(na) || Number.isNaN(nb)) {
      // A prerelease identifier sorts below the release of the same numbers.
      if (pa[i] === pb[i]) continue;
      if (pa[i] === undefined) return 1;
      if (pb[i] === undefined) return -1;
      return pa[i] < pb[i] ? -1 : 1;
    }
    if (na !== nb) return na - nb;
  }
  return 0;
}

function renderPage(rel) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Crowe Logic releases</title>
<meta name="description" content="Download the Crowe Logic desktop app for Windows, macOS, and Linux." />
<link rel="icon" type="image/svg+xml" href="${MARK_ICON}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
<style>
:root { --paper:#f7f3ea; --panel:#fdfbf5; --ink:#1a1714; --gold:#b8893a; --dim:#6b6457; --line:rgba(26,23,20,.12); }
* { box-sizing:border-box; margin:0; }
body { background:var(--paper); color:var(--ink); font-family:Inter,system-ui,sans-serif; line-height:1.6; }
.wrap { max-width:920px; margin:0 auto; padding:0 24px; }
header { border-bottom:1px solid var(--line); }
header .wrap { display:flex; align-items:center; gap:12px; padding-top:16px; padding-bottom:16px; }
header .mark { width:28px; height:28px; }
header .name { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:18px; }
header .tag { font-family:'JetBrains Mono',monospace; font-size:11px; color:var(--dim); border:1px solid var(--line); border-radius:999px; padding:2px 10px; margin-left:4px; }
main { padding:56px 0 64px; }
h1 { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:40px; line-height:1.1; letter-spacing:-0.01em; }
.sub { color:var(--dim); font-size:15px; max-width:560px; margin:16px 0 8px; }
.ver { display:inline-block; font-family:'JetBrains Mono',monospace; font-size:12px; color:var(--gold); border:1px solid var(--gold); border-radius:999px; padding:2px 12px; margin:8px 0 40px; }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:16px; }
.card { background:var(--panel); border:1px solid var(--line); border-radius:14px; padding:24px; display:flex; flex-direction:column; gap:12px; }
.card h2 { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:20px; }
.card .meta { font-family:'JetBrains Mono',monospace; font-size:11.5px; color:var(--dim); }
.card p { font-size:13.5px; color:var(--dim); flex:1; }
.btn { display:inline-block; background:var(--ink); color:var(--paper); text-decoration:none; font-size:14px; font-weight:500; border-radius:10px; padding:10px 18px; text-align:center; }
.btn:hover { background:var(--gold); }
.alt { font-size:13px; }
.alt a { color:var(--gold); }
code, pre { font-family:'JetBrains Mono',monospace; font-size:12px; }
pre { background:#17150f; color:#e9e2cf; border-radius:8px; padding:10px 14px; overflow-x:auto; }
.note { border-left:2px solid var(--gold); padding-left:14px; margin-top:24px; font-size:13px; color:var(--dim); }
section.checks { margin-top:56px; border-top:1px solid var(--line); padding-top:32px; }
section.checks h3 { font-family:Fraunces,Georgia,serif; font-size:18px; font-weight:600; margin-bottom:8px; }
section.checks p { font-size:13.5px; color:var(--dim); margin-bottom:10px; }
section.presale { margin:48px 0 0; background:var(--panel); border:1px solid var(--gold); border-radius:14px; padding:28px; }
section.presale .eyebrow { font-family:'JetBrains Mono',monospace; font-size:11px; letter-spacing:.12em; text-transform:uppercase; color:var(--gold); margin-bottom:10px; }
section.presale h2 { font-family:Fraunces,Georgia,serif; font-size:26px; font-weight:600; margin-bottom:10px; }
section.presale p { font-size:14px; color:var(--dim); max-width:600px; }
section.presale .price { font-family:Fraunces,Georgia,serif; font-size:22px; margin:14px 0 4px; }
section.presale .price small { font-size:13px; color:var(--dim); font-family:Inter,system-ui,sans-serif; }
section.presale form { display:flex; gap:10px; margin-top:16px; flex-wrap:wrap; }
section.presale input[type=email] { flex:1; min-width:220px; border:1px solid var(--line); border-radius:10px; padding:10px 14px; font-size:14px; font-family:Inter,system-ui,sans-serif; background:#fff; }
section.presale button { background:var(--gold); color:#fff; border:0; border-radius:10px; padding:10px 22px; font-size:14px; font-weight:600; cursor:pointer; }
section.presale button:hover { background:var(--ink); }
section.presale .err { color:#a33; font-size:13px; margin-top:10px; display:none; }
footer { border-top:1px solid var(--line); padding:24px 0 40px; color:var(--dim); font-size:12.5px; }
footer .wrap { display:flex; justify-content:space-between; gap:16px; flex-wrap:wrap; }
</style>
</head>
<body>
<header>
  <div class="wrap">
    ${MARK_SVG}
    <span class="name">Crowe Logic</span>
    <span class="tag">releases</span>
  </div>
</header>
<main>
  <div class="wrap">
    <h1>Crowe Logic desktop</h1>
    <p class="sub">The operator for your workspace. Chat, a real terminal, reviewable edits, and an in-app browser, signed in with your Crowe ID.</p>
    <span class="ver">v${rel.version}</span>
    <div class="grid">
      ${card("Windows", "64-bit installer", "Run the installer and follow the setup prompts. Windows may show a SmartScreen warning while code-signing validation is completed.", rel, rel.windows)}
      ${card("macOS", "Apple Silicon dmg", "Open the dmg and drag Crowe Logic to Applications. The dmg and the app inside it are Developer ID signed, Apple notarized, and stapled.", rel, rel.macos, rel.macosIntel, "Download for Intel")}
      ${card("Linux", "x86_64 AppImage and deb", "Mark the AppImage executable and run it, or install the deb with apt.", rel, rel.appimage, rel.deb, "Download deb")}
    </div>
    <section class="checks">
      <h3>Verify your download</h3>
      <p>With <a style="color:var(--gold)" href="${href(rel.version, "SHA256SUMS")}">SHA256SUMS</a> in your download folder:</p>
      <pre>sha256sum -c SHA256SUMS --ignore-missing</pre>
    </section>
  </div>
</main>
<footer>
  <div class="wrap">
    <span>Crowe Logic, Inc.</span>
    <span>Questions: michael@crowelogic.com</span>
  </div>
</footer>
</body>
</html>`;
}

const TYPES = {
  ".exe": "application/octet-stream",
  ".dmg": "application/octet-stream",
  ".deb": "application/octet-stream",
  ".AppImage": "application/octet-stream",
  ".md": "text/markdown; charset=utf-8",
  ".png": "image/png",
};

function contentTypeFor(key, stored) {
  if (stored && stored !== "application/octet-stream") return stored;
  const ext = Object.keys(TYPES).find((e) => key.endsWith(e));
  return ext ? TYPES[ext] : stored || "application/octet-stream";
}

// electron-updater resolves the `url` of each file in latest-*.yml relative to
// the feed, which is desktop/channel/<os>/. The installers themselves are stored
// once per release under desktop/<version>/, so that lookup misses and every
// update download 404s. Rather than storing a second copy of a 120 MB installer
// per channel, map the miss back onto the versioned key using the version in the
// filename.
//
// The three platforms disagree on naming, so the version is delimited differently
// in each: CroweLogic-0.14.0-arm64.dmg, Crowe.Logic-0.14.0.AppImage,
// crowe-logic-desktop_0.14.0_amd64.deb, Crowe Logic Setup 0.14.0.exe.
//
// A plain release is stored under x.y.z, but a prerelease tag such as v0.15.0-rc.1
// is stored under the full identifier, and by inspection alone a trailing
// prerelease is indistinguishable from an arch suffix. So return candidates,
// shortest first, and let the bucket decide.
function versionedKeysFor(key) {
  const m = /^desktop\/channel\/[^/]+\/([^/]+)$/.exec(key);
  if (!m) return [];
  const name = m[1];
  if (name.startsWith("latest")) return [];

  const v = /(?:^|[-_. ])(\d+\.\d+\.\d+)(?:-([0-9A-Za-z.]+))?(?=[-_. ]|$)/.exec(name);
  if (!v) return [];

  const keys = [`desktop/${v[1]}/${name}`];
  if (v[2]) keys.push(`desktop/${v[1]}-${v[2]}/${name}`);
  return keys;
}

// Publishing a release means moving ~500 MB into the bucket, and the release
// machine is whatever laptop notarized the macOS build. Cloudflare's object API
// refuses bodies that size on some networks: v0.21.0's macOS artifacts failed
// fifteen times running from a residential uplink, while GitHub had accepted the
// very same files without complaint. Sized PUTs died in under 200ms, before a
// byte was sent, and streaming only raised the ceiling rather than removing it.
//
// Nothing about the files is the problem. The direction is. So pull instead of
// push: hand this endpoint an asset id on this repo's GitHub release and it
// copies the object in over Cloudflare's own network, GitHub to R2, with only a
// small JSON request crossing the release machine's uplink.
//
// The endpoint does not exist unless INGEST_TOKEN is set (wrangler secret put
// INGEST_TOKEN), it holds no GitHub credential of its own - the caller supplies
// one per request - and it cannot be aimed anywhere but this repo's own release
// assets, because the source url is built here from an integer id rather than
// accepted from the caller.
const INGEST_REPO = "MichaelCrowe11/crowe-logic-desktop";

function safeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string" || a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// Only the two shapes publish-r2.sh writes: desktop/<version>/<file> and
// desktop/channel/<os>/<file>. Segments are matched against a literal set of
// characters, so "..", a leading slash and an empty segment are all unmatchable
// rather than filtered out afterwards.
function validIngestKey(key) {
  const seg = /^[A-Za-z0-9][A-Za-z0-9._ -]*$/;
  const parts = key.split("/");
  if (parts.length < 3 || parts.length > 4) return false;
  if (parts[0] !== "desktop") return false;
  if (parts.length === 4 && parts[1] !== "channel") return false;
  return parts.slice(1).every((p) => seg.test(p) && !p.includes(".."));
}

async function ingest(request, env) {
  if (!env.INGEST_TOKEN) return new Response("Not found", { status: 404 });
  if (!safeEqual(request.headers.get("x-ingest-token") || "", env.INGEST_TOKEN)) {
    return new Response("Forbidden", { status: 403 });
  }

  const githubToken = request.headers.get("x-github-token") || "";
  if (!githubToken) return new Response("Missing x-github-token", { status: 400 });

  let body;
  try {
    body = await request.json();
  } catch {
    return new Response("Expected a JSON body", { status: 400 });
  }
  const key = String(body.key || "");
  const assetId = body.assetId;
  const expected = body.size;
  if (!validIngestKey(key)) return new Response(`Refusing key: ${key}`, { status: 400 });
  if (!Number.isInteger(assetId) || assetId <= 0) return new Response("assetId must be a positive integer", { status: 400 });

  // GitHub answers the asset api with a redirect to a signed storage url, and
  // forwarding the Authorization header on to that host is both unnecessary and
  // rejected by it. Follow the hop by hand so the credential stops here.
  const head = await fetch(`https://api.github.com/repos/${INGEST_REPO}/releases/assets/${assetId}`, {
    headers: {
      authorization: `Bearer ${githubToken}`,
      accept: "application/octet-stream",
      "user-agent": "crowe-releases-ingest",
    },
    redirect: "manual",
  });
  const location = head.headers.get("location");
  const source = location ? await fetch(location) : head;
  if (!source.ok || !source.body) {
    return new Response(`GitHub returned ${source.status} for asset ${assetId}`, { status: 502 });
  }

  const written = await env.RELEASES.put(key, source.body, {
    httpMetadata: { contentType: contentTypeFor(key, null) },
  });

  // A truncated copy is worse than a missing one: the feed would name it, the
  // updater would download it, and the signature check would fail on a user's
  // machine with nothing to point at. Refuse to leave a short object behind.
  if (Number.isInteger(expected) && written.size !== expected) {
    await env.RELEASES.delete(key);
    return new Response(`Wrote ${written.size} bytes, expected ${expected} - deleted`, { status: 502 });
  }

  return Response.json({ key, size: written.size, etag: written.httpEtag });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname);

    if (path === "/_ingest" && request.method === "POST") return ingest(request, env);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
    }

    if (path === "/" || path === "/index.html") {
      const rel = await catalog(env);
      if (!rel) return new Response("No release published yet", { status: 503 });
      return new Response(request.method === "HEAD" ? null : renderPage(rel), {
        headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300" },
      });
    }

    if (path.startsWith("/desktop/") || path.startsWith("/brand/")) {
      const key = path.slice(1);
      // electron-updater asks for byte ranges when it applies a blockmap diff,
      // so serving the whole object with a 200 would defeat the differential
      // download the blockmaps exist for. Let R2 do the slicing.
      const range = request.headers.get("range") || undefined;
      const options = range ? { range: request.headers } : undefined;

      let object = await env.RELEASES.get(key, options);
      for (const alt of object ? [] : versionedKeysFor(key)) {
        object = await env.RELEASES.get(alt, options);
        if (object) break;
      }
      if (!object) return new Response("Not found", { status: 404 });

      const headers = new Headers();
      object.writeHttpMetadata(headers);
      headers.set("content-type", contentTypeFor(key, headers.get("content-type")));
      headers.set("etag", object.httpEtag);
      headers.set("cache-control", "public, max-age=3600");
      headers.set("accept-ranges", "bytes");

      let status = 200;
      if (object.range && range) {
        const offset = object.range.offset ?? 0;
        const length = object.range.length ?? object.size - offset;
        headers.set("content-range", `bytes ${offset}-${offset + length - 1}/${object.size}`);
        headers.set("content-length", String(length));
        status = 206;
      } else {
        headers.set("content-length", String(object.size));
      }

      if (request.method === "HEAD") { object.body?.cancel?.(); return new Response(null, { status, headers }); }
      return new Response(object.body, { status, headers });
    }

    return new Response("Not found", { status: 404 });
  },
};
