// Crowe Logic release site: branded download page at "/", installer objects
// streamed from the crowe-releases R2 bucket under /desktop/* and /brand/*.

// Inline copy of assets/mark.svg (generated by scripts/gen-mark.js) so the page
// renders its logo without an R2 brand object; re-inline if the mark regenerates.
const MARK_SVG = `<svg class="mark" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <polygon points="62.39,7.07 60.00,5.69 12.96,32.84 27.36,41.16 60.00,22.31 62.39,23.69" fill="#3766C0"/>
  <polygon points="12.96,32.84 12.96,87.16 27.36,78.84 27.36,41.16" fill="#2E5AAD"/>
  <polygon points="12.96,87.16 60.00,114.31 95.85,93.61 95.85,76.99 60.00,97.69 27.36,78.84" fill="#274C97"/>
  <polygon points="62.39,18.04 60.00,16.66 22.47,38.33 22.47,81.67 60.00,103.34 95.85,82.64 95.85,76.99 60.00,97.69 27.36,78.84 27.36,41.16 60.00,22.31 62.39,23.69" fill="#13294F"/>
  <polygon points="92.64,54.04 107.04,45.72 107.04,64.12 92.64,72.44" fill="#2E5AAD"/>
  <polygon points="92.64,54.04 97.53,51.21 97.53,69.61 92.64,72.44" fill="#13294F"/>
  <polygon points="69.68,99.59 42.16,83.71 55.76,75.85 69.68,83.89" fill="#CE8710"/>
  <polygon points="42.16,83.71 42.16,45.03 67.82,30.22 67.82,45.92 55.76,52.89 55.76,75.85" fill="#EFA71B"/>
  <polygon points="51.14,78.52 51.14,50.22 67.82,40.58 67.82,45.92 55.76,52.89 55.76,75.85" fill="#A96F08"/>
  <polygon points="67.02,24.73 106.46,38.07 67.02,51.41" fill="#EFA71B"/>
  <polygon points="67.02,51.41 106.46,38.07 107.27,40.48 67.83,53.82" fill="#A96F08"/>
</svg>`;
const MARK_ICON = "data:image/svg+xml," + encodeURIComponent(MARK_SVG.replace(' class="mark"', ""));

function href(version, name) {
  return `/desktop/${encodeURIComponent(version)}/${encodeURIComponent(name)}`;
}

function escapeHtml(s) {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
}

function card(title, meta, body, rel, primary, secondary, secondaryLabel) {
  const buttons = primary
    ? `<a class="btn" href="${href(rel.version, primary)}">Download for ${escapeHtml(title)}</a>` +
      (secondary ? `\n        <span class="alt"><a href="${href(rel.version, secondary)}">${escapeHtml(secondaryLabel)}</a></span>` : "")
    : `<span class="meta">Not in this release</span>`;
  return `<div class="card">
        <h2>${escapeHtml(title)}</h2>
        <span class="meta">${escapeHtml(meta)}</span>
        <p>${escapeHtml(body)}</p>
        ${buttons}
      </div>`;
}

// The page used to hardcode a version and installer filenames, which drifted
// three releases out of date and linked a Windows installer that had never been
// built under that name. Read the channel manifests the updater reads instead,
// so the page cannot disagree with what was actually published.
async function readManifest(env, key) {
  const object = await env.RELEASES.get(key);
  if (!object) return null;
  const text = await object.text();
  const version = /^version:\s*(\S+)/m.exec(text);
  if (!version) return null;
  return { version: version[1], files: [...text.matchAll(/^\s+- url:\s*(.+?)\s*$/gm)].map((m) => m[1]) };
}

async function catalog(env) {
  // These paths must match electron-builder's ${os} macro in the publish url,
  // which expands to mac, win and linux.
  const [mac, win, lin] = await Promise.all([
    readManifest(env, "desktop/channel/mac/latest-mac.yml"),
    readManifest(env, "desktop/channel/win/latest.yml"),
    readManifest(env, "desktop/channel/linux/latest-linux.yml"),
  ]);

  // Platforms can lag each other, so show the newest version any of them
  // reached and only offer the installers that belong to it.
  const versions = [mac, win, lin].filter(Boolean).map((m) => m.version);
  if (versions.length === 0) return null;
  const version = versions.sort(compareVersions).pop();
  const at = (m) => (m && m.version === version ? m.files : []);
  const pick = (m, re) => at(m).find((f) => re.test(f)) || null;

  return {
    version,
    windows: pick(win, /\.exe$/),
    macos: pick(mac, /\.dmg$/),
    appimage: pick(lin, /\.AppImage$/),
    deb: pick(lin, /\.deb$/),
  };
}

function compareVersions(a, b) {
  const pa = a.split(/[.-]/);
  const pb = b.split(/[.-]/);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const na = Number(pa[i]);
    const nb = Number(pb[i]);
    if (Number.isNaN(na) || Number.isNaN(nb)) {
      // A prerelease identifier sorts below the release of the same numbers.
      if (pa[i] === pb[i]) continue;
      if (pa[i] === undefined) return 1;
      if (pb[i] === undefined) return -1;
      return pa[i] < pb[i] ? -1 : 1;
    }
    if (na !== nb) return na - nb;
  }
  return 0;
}

function renderPage(rel) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Crowe Logic releases</title>
<meta name="description" content="Download the Crowe Logic desktop app for Windows, macOS, and Linux." />
<link rel="icon" type="image/svg+xml" href="${MARK_ICON}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
<style>
:root { --paper:#f7f3ea; --panel:#fdfbf5; --ink:#1a1714; --gold:#b8893a; --dim:#6b6457; --line:rgba(26,23,20,.12); }
* { box-sizing:border-box; margin:0; }
body { background:var(--paper); color:var(--ink); font-family:Inter,system-ui,sans-serif; line-height:1.6; }
.wrap { max-width:920px; margin:0 auto; padding:0 24px; }
header { border-bottom:1px solid var(--line); }
header .wrap { display:flex; align-items:center; gap:12px; padding-top:16px; padding-bottom:16px; }
header .mark { width:28px; height:28px; }
header .name { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:18px; }
header .tag { font-family:'JetBrains Mono',monospace; font-size:11px; color:var(--dim); border:1px solid var(--line); border-radius:999px; padding:2px 10px; margin-left:4px; }
main { padding:56px 0 64px; }
h1 { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:40px; line-height:1.1; letter-spacing:-0.01em; }
.sub { color:var(--dim); font-size:15px; max-width:560px; margin:16px 0 8px; }
.ver { display:inline-block; font-family:'JetBrains Mono',monospace; font-size:12px; color:var(--gold); border:1px solid var(--gold); border-radius:999px; padding:2px 12px; margin:8px 0 40px; }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:16px; }
.card { background:var(--panel); border:1px solid var(--line); border-radius:14px; padding:24px; display:flex; flex-direction:column; gap:12px; }
.card h2 { font-family:Fraunces,Georgia,serif; font-weight:600; font-size:20px; }
.card .meta { font-family:'JetBrains Mono',monospace; font-size:11.5px; color:var(--dim); }
.card p { font-size:13.5px; color:var(--dim); flex:1; }
.btn { display:inline-block; background:var(--ink); color:var(--paper); text-decoration:none; font-size:14px; font-weight:500; border-radius:10px; padding:10px 18px; text-align:center; }
.btn:hover { background:var(--gold); }
.alt { font-size:13px; }
.alt a { color:var(--gold); }
code, pre { font-family:'JetBrains Mono',monospace; font-size:12px; }
pre { background:#17150f; color:#e9e2cf; border-radius:8px; padding:10px 14px; overflow-x:auto; }
.note { border-left:2px solid var(--gold); padding-left:14px; margin-top:24px; font-size:13px; color:var(--dim); }
section.checks { margin-top:56px; border-top:1px solid var(--line); padding-top:32px; }
section.checks h3 { font-family:Fraunces,Georgia,serif; font-size:18px; font-weight:600; margin-bottom:8px; }
section.checks p { font-size:13.5px; color:var(--dim); margin-bottom:10px; }
section.presale { margin:48px 0 0; background:var(--panel); border:1px solid var(--gold); border-radius:14px; padding:28px; }
section.presale .eyebrow { font-family:'JetBrains Mono',monospace; font-size:11px; letter-spacing:.12em; text-transform:uppercase; color:var(--gold); margin-bottom:10px; }
section.presale h2 { font-family:Fraunces,Georgia,serif; font-size:26px; font-weight:600; margin-bottom:10px; }
section.presale p { font-size:14px; color:var(--dim); max-width:600px; }
section.presale .price { font-family:Fraunces,Georgia,serif; font-size:22px; margin:14px 0 4px; }
section.presale .price small { font-size:13px; color:var(--dim); font-family:Inter,system-ui,sans-serif; }
section.presale form { display:flex; gap:10px; margin-top:16px; flex-wrap:wrap; }
section.presale input[type=email] { flex:1; min-width:220px; border:1px solid var(--line); border-radius:10px; padding:10px 14px; font-size:14px; font-family:Inter,system-ui,sans-serif; background:#fff; }
section.presale button { background:var(--gold); color:#fff; border:0; border-radius:10px; padding:10px 22px; font-size:14px; font-weight:600; cursor:pointer; }
section.presale button:hover { background:var(--ink); }
section.presale .err { color:#a33; font-size:13px; margin-top:10px; display:none; }
footer { border-top:1px solid var(--line); padding:24px 0 40px; color:var(--dim); font-size:12.5px; }
footer .wrap { display:flex; justify-content:space-between; gap:16px; flex-wrap:wrap; }
</style>
</head>
<body>
<header>
  <div class="wrap">
    ${MARK_SVG}
    <span class="name">Crowe Logic</span>
    <span class="tag">releases</span>
  </div>
</header>
<main>
  <div class="wrap">
    <h1>Crowe Logic desktop</h1>
    <p class="sub">The operator for your workspace. Chat, a real terminal, reviewable edits, and an in-app browser, signed in with your Crowe ID.</p>
    <span class="ver">v${rel.version}</span>
    <div class="grid">
      ${card("Windows", "64-bit installer", "Run the installer and follow the setup prompts. Windows may show a SmartScreen warning while code-signing validation is completed.", rel, rel.windows)}
      ${card("macOS", "Apple Silicon dmg", "Open the dmg and drag Crowe Logic to Applications. The dmg and the app inside it are Developer ID signed, Apple notarized, and stapled.", rel, rel.macos)}
      ${card("Linux", "x86_64 AppImage and deb", "Mark the AppImage executable and run it, or install the deb with apt.", rel, rel.appimage, rel.deb, "Download deb")}
    </div>
    <section class="checks">
      <h3>Verify your download</h3>
      <p>With <a style="color:var(--gold)" href="${href(rel.version, "SHA256SUMS")}">SHA256SUMS</a> in your download folder:</p>
      <pre>sha256sum -c SHA256SUMS --ignore-missing</pre>
    </section>
  </div>
</main>
<footer>
  <div class="wrap">
    <span>Crowe Logic, Inc.</span>
    <span>Questions: michael@crowelogic.com</span>
  </div>
</footer>
</body>
</html>`;
}

const TYPES = {
  ".exe": "application/octet-stream",
  ".dmg": "application/octet-stream",
  ".deb": "application/octet-stream",
  ".AppImage": "application/octet-stream",
  ".md": "text/markdown; charset=utf-8",
  ".png": "image/png",
};

function contentTypeFor(key, stored) {
  if (stored && stored !== "application/octet-stream") return stored;
  const ext = Object.keys(TYPES).find((e) => key.endsWith(e));
  return ext ? TYPES[ext] : stored || "application/octet-stream";
}

// electron-updater resolves the `url` of each file in latest-*.yml relative to
// the feed, which is desktop/channel/<os>/. The installers themselves are stored
// once per release under desktop/<version>/, so that lookup misses and every
// update download 404s. Rather than storing a second copy of a 120 MB installer
// per channel, map the miss back onto the versioned key using the version in the
// filename.
//
// The three platforms disagree on naming, so the version is delimited differently
// in each: CroweLogic-0.14.0-arm64.dmg, Crowe.Logic-0.14.0.AppImage,
// crowe-logic-desktop_0.14.0_amd64.deb, Crowe Logic Setup 0.14.0.exe.
//
// A plain release is stored under x.y.z, but a prerelease tag such as v0.15.0-rc.1
// is stored under the full identifier, and by inspection alone a trailing
// prerelease is indistinguishable from an arch suffix. So return candidates,
// shortest first, and let the bucket decide.
function versionedKeysFor(key) {
  const m = /^desktop\/channel\/[^/]+\/([^/]+)$/.exec(key);
  if (!m) return [];
  const name = m[1];
  if (name.startsWith("latest")) return [];

  const v = /(?:^|[-_. ])(\d+\.\d+\.\d+)(?:-([0-9A-Za-z.]+))?(?=[-_. ]|$)/.exec(name);
  if (!v) return [];

  const keys = [`desktop/${v[1]}/${name}`];
  if (v[2]) keys.push(`desktop/${v[1]}-${v[2]}/${name}`);
  return keys;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const path = decodeURIComponent(url.pathname);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
    }

    if (path === "/" || path === "/index.html") {
      const rel = await catalog(env);
      if (!rel) return new Response("No release published yet", { status: 503 });
      return new Response(request.method === "HEAD" ? null : renderPage(rel), {
        headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=300" },
      });
    }

    if (path.startsWith("/desktop/") || path.startsWith("/brand/")) {
      const key = path.slice(1);
      // electron-updater asks for byte ranges when it applies a blockmap diff,
      // so serving the whole object with a 200 would defeat the differential
      // download the blockmaps exist for. Let R2 do the slicing.
      const range = request.headers.get("range") || undefined;
      const options = range ? { range: request.headers } : undefined;

      let object = await env.RELEASES.get(key, options);
      for (const alt of object ? [] : versionedKeysFor(key)) {
        object = await env.RELEASES.get(alt, options);
        if (object) break;
      }
      if (!object) return new Response("Not found", { status: 404 });

      const headers = new Headers();
      object.writeHttpMetadata(headers);
      headers.set("content-type", contentTypeFor(key, headers.get("content-type")));
      headers.set("etag", object.httpEtag);
      headers.set("cache-control", "public, max-age=3600");
      headers.set("accept-ranges", "bytes");

      let status = 200;
      if (object.range && range) {
        const offset = object.range.offset ?? 0;
        const length = object.range.length ?? object.size - offset;
        headers.set("content-range", `bytes ${offset}-${offset + length - 1}/${object.size}`);
        headers.set("content-length", String(length));
        status = 206;
      } else {
        headers.set("content-length", String(object.size));
      }

      if (request.method === "HEAD") { object.body?.cancel?.(); return new Response(null, { status, headers }); }
      return new Response(object.body, { status, headers });
    }

    return new Response("Not found", { status: 404 });
  },
};
