// Crowe Logic living mark — the corporate double-C hex cube, alive.
// Geometry comes from renderer/mark-geometry.js (generated by scripts/gen-mark.js):
// a blue hexagonal C + right-face stub interlocked with a gold inner C whose
// shaft fires an arrow out the upper-right edge. States:
//   rest       still
//   idle       slow breath (welcome hero)
//   reasoning  the arrow assembly works: piston drive + gold heat
//   ping()     one-shot hexagonal ring + arrow micro-fire on each tool call
//
// window.CroweMark:
//   svg()                -> SVG markup string
//   mount(el, {state})   -> { el, setState(s), ping(), rest() }
//   setState(el, state)  -> 'idle' | 'reasoning' | 'rest'
//   ping(el)             -> one-shot tool ring
//   start()/stop()/reseed() kept for API compatibility (no-ops: the corporate
//   palette is fixed; identity does not drift).
(function () {
  "use strict";
  const G = window.CROWE_MARK_GEOMETRY;

  function svg() {
    if (!G) return "";
    const seg = (s) => `<polygon points="${s.pts}" fill="${s.fill}"/>`;
    return `<svg class="cl-mk" viewBox="0 0 ${G.view} ${G.view}" aria-hidden="true">`
      + `<polygon class="cm-ping" points="${G.hex}" fill="none" stroke="#E8A317" stroke-width="2.5"/>`
      + `<g class="cm-all">`
      + `<g class="cm-blue">`
      + G.blue.segs.map(seg).join("")
      + `<polygon class="cm-lip" points="${G.blue.lip.pts}" fill="${G.blue.lip.fill}"/>`
      + `<polygon points="${G.blue.stub.pts}" fill="#2E5AAD"/>`
      + `<polygon class="cm-lip" points="${G.blue.stub.lip}" fill="#13294F"/>`
      + `</g>`
      + `<g class="cm-gold">`
      + G.gold.segs.map(seg).join("")
      + `<polygon class="cm-lip" points="${G.gold.lip.pts}" fill="${G.gold.lip.fill}"/>`
      + `<polygon points="${G.gold.head}" fill="#EFA71B"/>`
      + `<polygon class="cm-lip" points="${G.gold.headLip}" fill="#A96F08"/>`
      + `</g></g></svg>`;
  }

  function ping(el) { if (!el) return; el.classList.remove("cl-ping-on"); void el.offsetWidth; el.classList.add("cl-ping-on"); }
  function setState(el, state) { if (el) el.dataset.state = state; }

  function mount(el, opts) {
    opts = opts || {};
    el.classList.add("cl-mark");
    el.innerHTML = svg();
    // Tiny mounts drop the fold-shade lips: cleaner silhouette below ~30px.
    requestAnimationFrame(() => { if (el.clientWidth && el.clientWidth < 30) el.classList.add("cm-small"); });
    setState(el, opts.state || "rest");
    return {
      el,
      setState: (s) => setState(el, s),
      ping: () => ping(el),
      rest: () => setState(el, "rest"),
    };
  }

  const noop = () => {};
  window.CroweMark = { svg, mount, setState, ping, start: noop, stop: noop, reseed: noop };
})();
