// Crowe Logic living mark: the Gate Glyph, alive.
//
// This is the ONLY mark animator in the app. It used to animate the whorl (six
// hyphae around a spore); since the Master Brand Directive of 2026-09-19 the
// app mark is the Gate Glyph, and the whorl lives on only inside the wordmark.
// Two jaws frame an aperture, a brass core sits in the aperture while the gate
// is open, and the jaws close when something has gone wrong.
//
// Geometry comes from renderer/mark-geometry.js (generated by
// scripts/gen-mark.js), so the animated mark and the shipped icon are the same
// four strings. The fallback below is the same geometry, for a page that loads
// this file without the module.
//
// States (the directive: motion is state, never decoration, and nothing moves
// perpetually):
//   rest       open, still
//   idle       open, still (kept as a distinct name for callers)
//   reasoning  the core pulses, the execution beat
//   failed     the jaws close, the core goes, colour drains to muted
//   ping()     one-shot ring on each tool landing
//
// window.CroweMark:
//   svg(opts)                -> SVG markup string
//   mount(el, {state})       -> { el, setState(s), ping(), rest() }
//   setState(el, state)      -> 'rest' | 'idle' | 'reasoning' | 'failed'
//   ping(el)                 -> one-shot tool ring
//   `small` is accepted and ignored: the glyph reads at 16px, so one cut serves
//   every slot. start()/stop()/reseed() are kept for API compatibility (no-ops).
(function () {
  "use strict";
  const G = window.CROWE_MARK_GEOMETRY;
  const GATE = (G && G.gate) || {
    viewBox: "3.5 0 64 64",
    jawC: "M41.31,47.76 A20,20 0 1 1 41.31,16.24",
    jawL: "M48,12 h8 v40 h-8 z M48,44 h15 v8 h-15 z",
    core: "37.63,35.25 32.00,38.50 26.37,35.25 26.37,28.75 32.00,25.50 37.63,28.75",
    ink: { x: 8, y: 8, w: 55, h: 48 },
  };
  const cx = GATE.ink.x + GATE.ink.w / 2, cy = GATE.ink.y + GATE.ink.h / 2;

  /* Jaws in currentColor so the host's colour (--ink, or --muted when failed)
     is the drawing's; the core takes --gold through .cm-heart in styles.css.
     No inline style attributes: the shells run under a CSP that forbids them,
     and every colour, delay and motion is a class resolved by the stylesheet.
     The ping ring is authored outside the ink box on purpose; .cl-mk sets
     overflow: visible and it animates out to 2.4x regardless. */
  function svg() {
    return `<svg class="cl-mk" viewBox="${GATE.viewBox}" aria-hidden="true">`
      + `<circle class="cm-ping" cx="${cx}" cy="${cy}" r="30" fill="none" stroke-width="2"/>`
      + `<g class="cm-gate">`
      + `<path class="cm-jaw cm-jaw-c" d="${GATE.jawC}" fill="none" stroke="currentColor" stroke-width="8" stroke-linecap="butt"/>`
      + `<path class="cm-jaw cm-jaw-l" d="${GATE.jawL}" fill="currentColor"/>`
      + `<polygon class="cm-heart" points="${GATE.core}"/>`
      + `</g></svg>`;
  }

  function ping(el) { if (!el) return; el.classList.remove("cl-ping-on"); void el.offsetWidth; el.classList.add("cl-ping-on"); }
  function setState(el, state) { if (el) el.dataset.state = state; }

  function mount(el, opts) {
    opts = opts || {};
    el.classList.add("cl-mark");
    el.innerHTML = svg();
    setState(el, opts.state || "rest");
    return {
      el,
      setState: (s) => setState(el, s),
      ping: () => ping(el),
      rest: () => setState(el, "rest"),
    };
  }

  const noop = () => {};
  window.CroweMark = { svg, mount, setState, ping, start: noop, stop: noop, reseed: noop };
})();
