#!/usr/bin/env python3
"""Cut the app icon's letter out of the logotype's own typeface.

The icon used to be the hyphal mark on a dark tile. On a home screen beside
thirty other rounded squares that reads as a generic burst; what people
recognise as Crowe Logic is the lettering - the high-contrast Fraunces "C" the
wordmark opens with. So the icon is that letter, set from the same font at the
same axis coordinates gen-wordmark.py uses, with the spore in its aperture so
gold still appears exactly once.

This file cuts the letter. It does not compose the icon.

It used to do both, and that was the mistake: it wrote assets/icon-letter.svg
and icon-letter-foreground.svg, a second and independent composition of the same
app icon, hand-run and last regenerated in #34 - while scripts/gen-mark.js drew
its own from the same letter and moved on three times. The two disagreed on the
spore (this file scaled the corona hexagon 1.45; gen-mark.js drew it stock), so
"the app icon" was two different drawings depending on which platform you looked
at, and the one Android shipped was the frozen one. Both compositions live in
gen-mark.js now, which runs under plain node inside `npm run icons` and is held
to the rasters by `npm run icons:check`. The safe-zone reasoning that used to
sit here in COVER_ADAPTIVE moved with them, corrected: it compared a box SIDE
against a circle DIAMETER, and Android's mask makes the constraint a diagonal.

Outlined rather than set as <text>, for the reason gen-wordmark.py gives: an
SVG <text> resolves the family on the viewer's machine and falls back to
Georgia everywhere Fraunces is not installed. Outlines cannot drift.

Requires: fontTools. Run by hand when the letter or the type changes; the module
it writes is committed and reviewed like any other source.

    python3 scripts/gen-wordmark-icon.py
"""
import json
import pathlib
import sys

from fontTools.misc.transform import Transform
from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT = pathlib.Path.home() / "Library/Fonts/Fraunces[SOFT,WONK,opsz,wght].ttf"

LETTER = "C"
# Identical to gen-wordmark.py: the icon is a detail of the logotype, not a
# second interpretation of it.
COORDS = {"wght": 600, "opsz": 144, "SOFT": 0, "WONK": 1}

# Where the spore sits, in units of the letter's cap height, measured from the
# letter's centre. The C's aperture is the gap on its right flank; the spore
# rides in it rather than on the stroke, which would print gold on cream.
#
# Emitted rather than acted on: gen-mark.js places the spore from these numbers,
# so the placement is decided once, here, beside the letter it belongs to.
SPORE_X = 0.36
SPORE_Y = 0.00
SPORE_SIZE = 0.57


def contours(glyphset, name):
    rec = RecordingPen()
    glyphset[name].draw(rec)
    out, cur = [], []
    for op, args in rec.value:
        if op == "moveTo" and cur:
            out.append(cur)
            cur = []
        cur.append((op, args))
    if cur:
        out.append(cur)
    return out


def bounds(contour):
    xs, ys = [], []
    for _, args in contour:
        for pt in args:
            if isinstance(pt, tuple):
                xs.append(pt[0])
                ys.append(pt[1])
    return (min(xs), min(ys), max(xs), max(ys)) if xs else (0, 0, 0, 0)


def letter_path():
    """The letter as an SVG path, plus its drawn extents in SVG coordinates."""
    if not FONT.exists():
        sys.exit(f"missing {FONT} - install the full Fraunces first")
    font = instancer.instantiateVariableFont(
        TTFont(FONT), COORDS, inplace=False, updateFontNames=False)
    upem = font["head"].unitsPerEm
    name = font.getBestCmap()[ord(LETTER)]
    gs = font.getGlyphSet()

    boxes = [bounds(c) for c in contours(gs, name)]
    x0 = min(b[0] for b in boxes); x1 = max(b[2] for b in boxes)
    y0 = min(b[1] for b in boxes); y1 = max(b[3] for b in boxes)

    pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}")
    # Font units run up, SVG runs down.
    gs[name].draw(TransformPen(pen, Transform(1, 0, 0, -1, 0, 0)))
    return pen.getCommands(), {
        "x": x0, "y": -y1, "w": x1 - x0, "h": y1 - y0, "upem": upem,
    }


def letter_data_js(d, box):
    """The letter as a committed JS module, for gen-mark.js to place.

    The desktop tile is drawn by scripts/gen-mark.js, which runs under plain
    node with no dependencies — the same constraint gen-wordmark.py works
    around by baking wordmark-data.js. Handing it the outline the same way
    keeps `npm run icons` free of a Python toolchain, and keeps both apps
    wearing one letter cut from one font.
    """
    return (
        "// GENERATED by scripts/gen-wordmark-icon.py - do not edit by hand.\n"
        f"// '{LETTER}' outlined from Fraunces at {COORDS}.\n"
        "// `box` is the letter's drawn extents in the same SVG-down space as `d`.\n"
        "module.exports = " + json.dumps({
            "letter": LETTER, "coords": COORDS,
            "d": d,
            "box": {k: round(v, 4) for k, v in box.items()},
            "spore": {"x": SPORE_X, "y": SPORE_Y, "size": SPORE_SIZE},
        }, indent=1) + ";\n"
    )


def main():
    d, box = letter_path()
    out = ROOT / "scripts" / "letter-data.js"
    out.write_text(letter_data_js(d, box))
    print(f"wrote {out.relative_to(ROOT)}")
    print("\nNext: npm run icons")


main()
